name: Deploy Frontend to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/print-buddy-frontend          # Ruta donde tienes el repo en la RPi
            git pull
            docker build -t print-buddy-frontend ./app/
            docker stop print-buddy-frontend || true
            docker rm print-buddy-frontend || true 
            docker run -d -p 8080:80 --name print-buddy-frontend print-buddy-frontend